### ISSUE TITLE
Native crash reports missing symbol information (file name, line number, function name)

### ISSUE THREAD

**Issue by calvarez-ov** [firebase/firebase-android-sdk#1978]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Crashlytics ndk
  * Component version: crashlytics-gradle 2.3.0, crashlytics-ndk 17.2.1

#### Steps to reproduce:

* Build a release apk using crashlytics ndk and upload debugging symbols: `./gradlew clean assembleRelease uploadCrashlyticsSymbolFileRelease`
* Force a native crash in the app
* Expected behavior: crash appears in Firebase Crashlytics console with file and line number information. For example:
    ```
    Crashed: Thread #1 SIGSEGV 0x0000000000000000
    0 libc.so (Missing)
    1 liblinphone.so linphonecore.c - Line 2020 linphone_core_set_adaptive_rate_algorithm + 2020
    2 base.odex (Missing)
    3 (Missing)
    ```
* Actual behavior: crash appears in Firebase Crashlytics console with library `*.so` name and `Missing`. For example:
    ```
    Crashed: Thread #1 SIGSEGV 0x0000000000000018
    0 liblinphone.so (Missing)
    1 liblinphone.so (Missing)
    2 liblinphone.so (Missing)
    3 liblinphone.so (Missing)
    4 liblinphone.so (Missing)
    5 liblinphone.so (Missing)
    6 liblinphone.so (Missing)
    7 liblinphone.so (Missing)
    8 liblinphone.so (Missing)
    9 (Missing)
    ...
    63 libart.so (Missing)
    ```

#### Relevant Code:

Here's a sample app: https://github.com/libon/CrashObfuscationTest

It doesn't include native code, but it depends on a native library, linphone.
The sample project has a screen with a button, which when pressed, forces a crash in linphone by calling a method with a `null` value which isn't supported by linphone:

```kotlin
private fun forceCrash() {
    Factory.instance().setDebugMode(true, "Linphone")
    val core = Factory.instance().createCore(null, null, this.getApplicationContext())
    core.start()
    core.adaptiveRateAlgorithm = null
}
```

To upload the debugging symbols to crashlytics, it [extracts them from the debug artifact](https://github.com/libon/CrashObfuscationTest/blob/master/app/crashlytics_ndk_symbols.gradle) provided by linphone and copies them to the relevant folders specified by `strippedNativeLibsDir` and `unstrippedNativeLibsDir`.

Note, the crashes appear correctly with the file names and line numbers if Android Gradle Plugin `3.6.3` is used instead of `4.0.1`.

The problem also exists with Android Gradle Plugin `4.2.0-alpha10` (the latest version as of today)

**Comment by obsantos** [comment]
Any update on this? We are having the same issue

**Comment by calvarez-ov** [comment]
Haven't had symbol information in native crashes for months. This was first reported in [July](https://github.com/firebase/firebase-android-sdk/issues/1700#issuecomment-667135874). Really looking forward to being able to understand our crashes again, some day.

**Comment by marius-bardan** [comment]
seeing the same behavior. 
using `classpath 'com.android.tools.build:gradle:4.1.0'`, `'com.google.firebase:firebase-crashlytics-gradle:2.3.0'` with `"com.google.firebase:firebase-crashlytics-ndk:17.2.2"`.
been going through config bugs, outdated docs, symbols not being uploaded and now this. pretty exchausting and difficult to get some symbol info on native crashes.

**Comment by calvarez-ov** [comment]
Looks like this is fixed with:
* `com.google.firebase:firebase-crashlytics-ndk:17.3.0`
* `com.google.firebase:firebase-crashlytics-gradle:2.4.1`

I checked this using `com.android.tools.build:gradle:4.1.1` and gradle `6.7.1`

**Comment by TyMarc** [comment]
I can confirm that it works on my side too with: 

- com.google.firebase:firebase-crashlytics-ndk:17.3.0
- com.google.firebase:firebase-crashlytics-gradle:2.4.1

Using com.android.tools.build:gradle:4.1.0 and gradle wrapper 6.5

**Comment by fredericojssilva** [comment]
Not working for me with `firebase-crashlytics-ndk:17.3.0` and `firebase-crashlytics-gradle:2.4.1`
Still getting:
`Crashlytics could not find NDK build tasks on which to depend. You many need to manually enforce task dependencies for generateCrashlyticsSymbolFile`

Any clue?

**Comment by MassimoMessore** [comment]
> Looks like this is fixed with:
> 
>     * `com.google.firebase:firebase-crashlytics-ndk:17.3.0`
> 
>     * `com.google.firebase:firebase-crashlytics-gradle:2.4.1`
> 
> 
> I checked this using `com.android.tools.build:gradle:4.1.1` and gradle `6.7.1`

I've just tried using the same configuration and it still doesn't work.

Running `generateCrashlyticsSymbolFileProdRelease ` and `uploadCrashlyticsSymbolFileProdRelease` scripts respectively, .cSYM files are generated and uploaded correctly to the `firebasecrashlyticssymbols.googleapis.com` backend but native stack traces for both old and new crashes are still missing.

My project tree is structured like detailed here: https://github.com/firebase/firebase-android-sdk/issues/1700#issuecomment-659979712

**Comment by bidansinha-okta** [comment]
> * -Wl, --build-id
@MassimoMessore   Thanks for the update !

I have a few questions.
(1) How did you pass the -Wl, --build-id flags. I am using CmakeList.txt file 
```set( CMAKE_SHARED_LINKER_FLAGS "-Wl,--build-id" )```

(2) Looks like gradlew uploadCrashlyticsSymbolFile<BuildVariant> is able to upload the symbols successfully. I can see that a compressed file is generated and is uploaded. However, I am still not able to find the symbols in firebase. Do we need to configure anything in the Firebase console?

I am using:
```com.google.firebase:firebase-crashlytics:17.3.0
com.google.firebase:firebase-crashlytics-ndk:17.3.0
com.google.firebase:firebase-crashlytics-gradle:2.4.1```

**Comment by MassimoMessore** [comment]
Hi @bidansinha-okta 

> (1) How did you pass the -Wl, --build-id flags. I am using CmakeList.txt file

I'm not sure about Cmake, sorry. I use GNU Makefile and I just added the flag to my LDFLAGS.

> (2) Looks like gradlew uploadCrashlyticsSymbolFile is able to upload the symbols successfully. I can see that a compressed file is generated and is uploaded

Please check if the build id of your native lib is part of the name of the uploaded compressed file (e.g. `libname-aarch64-<build-id>.zip`). You can check the build id of your native lib using the `readelf` command of the Android NDK, like I explained in my [previous post](https://github.com/firebase/firebase-android-sdk/issues/1978#issuecomment-733039949).


> Do we need to configure anything in the Firebase console?

No, I didn't changed anything on that side.

**Comment by kmandrika** [comment]
FYI, if you are using firebase-crashlytics-ndk 17.3.0+ and firebase-crashlytics-gradle 2.4.1+, you no longer need to specify the stripped libs directory.
