### ISSUE TITLE
Null pointer exception on FirebaseInAppMessagingDisplay.onClick

### ISSUE THREAD

**Issue by TrayEdge** [firebase/firebase-android-sdk#2128]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1
  * Firebase Component: In-App Messaging
  * Component version: 19.1.1

#### Steps to reproduce:

I set up campaign which should show "Top banner" triggered by several events. From time to time I receive below crash. There are no reasonable reproduce steps.

#### Relevant Code:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.supportsCustomTabs(FirebaseInAppMessagingDisplay.java:564)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.launchUriIntent(FirebaseInAppMessagingDisplay.java:537)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.access$300(FirebaseInAppMessagingDisplay.java:80)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$3.onClick(FirebaseInAppMessagingDisplay.java:323)
       at android.view.View.performClick(View.java:5198)
       at android.view.View.onKeyUp(View.java:9879)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2833)
       at android.view.View.dispatchKeyEvent(View.java:9234)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1635)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at com.google.firebase.inappmessaging.display.internal.layout.FiamFrameLayout.dispatchKeyEvent(FiamFrameLayout.java:58)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4131)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4093)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3791)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3848)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3824)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3985)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2253)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1874)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1865)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2230)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:731)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)
```

**Comment by zjamshidi** [comment]
I'm getting the same crash:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.supportsCustomTabs(FirebaseInAppMessagingDisplay.java)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.launchUriIntent(FirebaseInAppMessagingDisplay.java)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.access$300(FirebaseInAppMessagingDisplay.java)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$3.onClick(FirebaseInAppMessagingDisplay.java)
       at android.view.View.performClick(View.java:5267)
       at android.view.View$PerformClick.run(View.java:21536)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Device** LAVA  iris 820 Android v6.0 
**Using flutter sdk** ``` firebase_in_app_messaging: ^0.2.1```

**Comment by stari4ek** [comment]
I got it on 
```
Brand: PHILIPS
Model: 4K UHD Razor Slim LED TV powered by Android™
Version: 5.1.1
```
It looks like `FirebaseInAppMessagingDisplay.supportsCustomTabs` is just broken and can not verify if custom tabs are supported on devices without support

**Comment by eldhosembabu** [comment]
This is fixed in PR : https://github.com/firebase/firebase-android-sdk/pull/2263

**Comment by davidmotson** [comment]
Closing as fixed. Feel free to re-open as necessary

**Comment by stari4ek** [comment]
Which firebase version got this fix?
still getting with `com.google.firebase:firebase-bom:26.3.0` (com.google.firebase:firebase-inappmessaging-display:19.1.3)

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.supportsCustomTabs(FirebaseInAppMessagingDisplay.java:564)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.launchUriIntent(FirebaseInAppMessagingDisplay.java:537)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay.access$300(FirebaseInAppMessagingDisplay.java:80)
       at com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay$3.onClick(FirebaseInAppMessagingDisplay.java:323)
       at android.view.View.performClick(View.java:5201)
       at android.view.View.onKeyUp(View.java:9887)
       at android.widget.TextView.onKeyUp(TextView.java:6222)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2826)
       at android.view.View.dispatchKeyEvent(View.java:9237)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
       at com.google.firebase.inappmessaging.display.internal.layout.FiamCardView.dispatchKeyEvent(FiamCardView.java:52)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4131)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4093)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3791)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3848)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3824)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3985)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2256)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1877)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1868)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2233)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:731)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)
```
