### ISSUE TITLE
FirebaseException "unable to resolve host" should be a FirebaseNetworkException

### ISSUE THREAD

**Issue by edenman** [firebase/firebase-android-sdk#2251]
### Step 2: Describe your environment

  * Android Studio version: Android Studio Arctic Fox | 2020.3.1 Canary 2
  * Firebase Component: Auth 
  * Component version: 20.0.0

### Step 3: Describe the problem

getIdToken is passing this `FirebaseException` to the failure listener of `getIdToken`.  The message clearly indicates it's a network issue, it would be better if the exception were a `FirebaseNetworkException` (I auto-retry on `FirebaseNetworkException`)

#### Steps to reproduce:

Not sure, I got this stacktrace report via Sentry.

#### Relevant Code:

```
com.google.firebase.FirebaseException: An internal error has occurred. [ Unable to resolve host "securetoken.googleapis.com":No address associated with hostname ]
	at com.google.firebase.auth.api.internal.zzem.zza(com.google.firebase:firebase-auth@@20.0.0:18)
	at com.google.firebase.auth.api.internal.zzfx.zza(com.google.firebase:firebase-auth@@20.0.0:21)
	at com.google.firebase.auth.api.internal.zzfq.zza(com.google.firebase:firebase-auth@@20.0.0:35)
	at com.google.firebase.auth.api.internal.zzfs.zza(com.google.firebase:firebase-auth@@20.0.0:74)
	at com.google.firebase.auth.api.internal.zzel.zza(com.google.firebase:firebase-auth@@20.0.0:61)
	at com.google.firebase.auth.api.internal.zzc.zza(com.google.firebase:firebase-auth@@20.0.0:3)
	at com.google.firebase.auth.api.internal.zzgb.zza(com.google.firebase:firebase-auth@@20.0.0:37)
	at com.google.firebase.auth.api.internal.zzfn.zza(com.google.firebase:firebase-auth@@20.0.0:41)
	at com.google.firebase.auth.api.internal.zza.zza(com.google.firebase:firebase-auth@@20.0.0:8)
	at com.google.firebase.auth.api.internal.zzep.zza(com.google.firebase:firebase-auth@@20.0.0:76)
	at com.google.firebase.auth.api.internal.zzbr.zza(com.google.firebase:firebase-auth@@20.0.0:24)
	at com.google.firebase.auth.api.internal.zzbq.accept(Unknown Source:6)
	at com.google.android.gms.common.api.internal.zacj.doExecute(com.google.android.gms:play-services-base@@17.1.0:2)
	at com.google.android.gms.common.api.internal.zaf.zac(com.google.android.gms:play-services-base@@17.1.0:6)
	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(com.google.android.gms:play-services-base@@17.1.0:167)
	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zab(com.google.android.gms:play-services-base@@17.1.0:139)
	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zabg(com.google.android.gms:play-services-base@@17.1.0:99)
	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zabe(com.google.android.gms:play-services-base@@17.1.0:40)
	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnected(com.google.android.gms:play-services-base@@17.1.0:19)
	at com.google.android.gms.common.internal.zaf.onConnected(com.google.android.gms:play-services-base@@17.1.0:2)
	at com.google.android.gms.common.internal.BaseGmsClient$zzg.zzj(com.google.android.gms:play-services-basement@@17.1.1:24)
	at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(com.google.android.gms:play-services-basement@@17.1.1:12)
	at com.google.android.gms.common.internal.BaseGmsClient$zzb.zzo(com.google.android.gms:play-services-basement@@17.1.1:11)
	at com.google.android.gms.common.internal.BaseGmsClient$zzc.handleMessage(com.google.android.gms:play-services-basement@@17.1.1:49)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at com.google.android.gms.internal.common.zzi.dispatchMessage(com.google.android.gms:play-services-basement@@17.1.1:8)
	at android.os.Looper.loop(Looper.java:237)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by sdelaysam** [comment]
Same happens in Airplane mode (not my link)
https://stackoverflow.com/questions/57780604/firebase-throwing-firebaseexception-instead-of-firebasenetworkexception-when-the
Support is trying to convince me that this is ok 👎

**Comment by savv** [comment]
The following are all error substrings that I get from firebase auth. If I understand correctly, they should all be mapped to an error code of 'auth/network-request-failed'. (Some of them might from iOS.)

'A network error (such as timeout, interrupted connection or unreachable host) has occurred.'
'No address associated with hostname'
'Connection reset by peer'
'Software caused connection abort'
'Failed to connect to'

**Comment by mikehardy** [comment]
registering other direction of cross-link where we're watching https://github.com/invertase/react-native-firebase/issues/4690

**Comment by malcolmdeck** [comment]
This fix was released in 20.0.3 - are we still seeing issues for this or similar stack traces? Otherwise I'll close it

**Comment by mikehardy** [comment]
Oh interesting - that's BoM 26.6.0 and the release notes don't indicate this was in there at all https://firebase.google.com/support/release-notes/android#bom_v26-6-0 ? So I had no reason to ask for reproduction again - I released react-native-firebase v11.0.0 which defaulted to BoM 26.6.0 on March 3rd though https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md#1100-2021-03-03 right after your release so it should be "out there" amongst a large enough population of users to know

I'll ask - thanks

**Comment by mikehardy** [comment]
Nothing but crickets on the linked issue in the react-native-firebase repo :shrug: - appears to be resolved, I hope it is...

**Comment by ReginFell** [comment]
We are still getting this in `firestore-auth 20.0.3`

`com.google.firebase.FirebaseException: An internal error has occurred. [ Failed to connect to securetoken.googleapis.com/216.58.213.170:443 ]`

**Comment by malcolmdeck** [comment]
@ReginFell yes, this was fixed in 20.0.4 :)

**Comment by malcolmdeck** [comment]
Ah, no I got my wires cross. This should have been fixed in 20.0.3. I'll reopen for now - please let me know if we have a way to repro this

**Comment by mikehardy** [comment]
Downstream in react-native-firebase the reporter listed these conditions:

```
auth().currentUser.getIdToken() fails with the following message:

Error: [auth/unknown] An internal error has occurred. [ Unable to resolve host \"securetoken.googleapis.com\":No address associated with hostname ]

If all of these:

    The device is offline (airplane mode, no reception, etc.)
    The current token is expired (> 1 hour since app was last opened)
    It's Android (I haven't experienced this on iPhone, but I can double check)

I would expect an error of the type Error: [auth/network-request-failed].

To preserve offline functionality, this check on [auth/network-request-failed] is important to me.
```

**Comment by mikehardy** [comment]
yes-recent-activity

**Comment by mikehardy** [comment]
hyperactive google-oss-bot settings for this repo, it's discouraging as a collaborating maintainer.

**Comment by yuchenshi** [comment]
@mikehardy disabled the bot for this thread :)

**Comment by sebastian-hoebarth** [comment]
Hey there, I use anonym auth for all clients and I get a lot of App crashes:
I'm on 'com.google.firebase:firebase-auth:20.0.4' but had that already in prev. releases as well.
I need a valid token to communicate with my own backend, therefore all clients are at least anonymous logged in and authtoken is refreshed if outdated. My Crashfree rate dropped by about 0.5% because if this FibreaseNetworkExceptions that can't be catched.

I don't know what do do, tried already to only call it if the client has internet connection but still happens.
I can't understand why you send out an Exception that can be catched on something like an Internet connection on a Mobile SDK, seems to me like a totally wrong decission.

`Fatal Exception: com.google.firebase.FirebaseNetworkException: A network error (such as timeout, interrupted connection or unreachable host) has occurred.
       at com.google.android.gms.internal.firebase-auth-api.zztt.zza(zztt.java:17)
       at com.google.android.gms.internal.firebase-auth-api.zzvb.zza(zzvb.java:9)
       at com.google.android.gms.internal.firebase-auth-api.zzvc.zzk(zzvc.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzuz.zzh(zzuz.java:25)
       at com.google.android.gms.internal.firebase-auth-api.zztq.zzk(zztq.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzpm.zza(zzpm.java:2)
       at com.google.android.gms.internal.firebase-auth-api.zzpl.zza(zzpl.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzvg.zza(zzvg.java:27)
       at com.google.android.gms.internal.firebase-auth-api.zzuq.zzh(zzuq.java:4)
       at com.google.android.gms.internal.firebase-auth-api.zzpm.zzb(zzpm.java:4)
       at com.google.android.gms.internal.firebase-auth-api.zzpy.zzM(zzpy.java:5)
       at com.google.android.gms.internal.firebase-auth-api.zzpy.zzD(zzpy.java:3)
       at com.google.android.gms.internal.firebase-auth-api.zztu.zzo(zztu.java:5)
       at com.google.android.gms.internal.firebase-auth-api.zzrv.accept(zzrv.java:4)
       at com.google.android.gms.common.api.internal.zacr.doExecute(zacr.java:1)
       at com.google.android.gms.common.api.internal.zag.zaf(zag.java:1)
       at com.google.android.gms.common.api.internal.zabl.zaG(zabl.java:2)
       at com.google.android.gms.common.api.internal.zabl.zaF(zabl.java:5)
       at com.google.android.gms.common.api.internal.zabl.zad(zabl.java:3)
       at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(GoogleApiManager.java:64)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)`

**Comment by ashique-perumbavoor** [comment]
I am also having the same kind of issue where the OTP is not sending if I am in some networks.

**Comment by TooensureMaster** [comment]
I don't know if this helps, but after about 1hr, I noticed I had no wifi. Reconnected and everything was back normal.

**Comment by lehcar09** [comment]
Hi folks! I tried reproducing this issue and I wasn’t encountering the issue anymore. The FirebaseException is now a FirebaseNetworkException.

I’ll be closing this issue now. Let us know if there’s any misunderstanding so we can re-open the issue. Or, Please feel free to open a new issue if this still occurs. Thanks!
