### ISSUE TITLE
Duplicate class com.google.firebase.iid.FirebaseInstanceIdReceiver found (BoM 31.0.0)

### ISSUE THREAD

**Issue by thatfiredev** [firebase/firebase-android-sdk#4206]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Dolphin
  * Firebase Component: Functions, Messaging
  * Component version: BoM 31.0.0

### [REQUIRED] Step 3: Describe the problem

After upgrading to the BoM 31.0.0, I see the following error in the [logcat](https://github.com/firebase/quickstart-android/actions/runs/3238251151/jobs/5306265665):

```
Duplicate class com.google.firebase.iid.FirebaseInstanceIdReceiver found in modules
firebase-iid-20.0.1-runtime (com.google.firebase:firebase-iid:20.0.1)
and firebase-messaging-23.1.0-runtime (com.google.firebase:firebase-messaging:23.1.0)
```

#### Steps to reproduce:

Add the BoM, firebase-messaging and firebase-functions dependencies:

```groovy
    implementation platform('com.google.firebase:firebase-bom:31.0.0')

    implementation 'com.google.firebase:firebase-functions'
    implementation 'com.google.firebase:firebase-messaging'
```

A current workaround is to also define the iid version explicitly:

```groovy
    implementation platform('com.google.firebase:firebase-bom:31.0.0')

    implementation 'com.google.firebase:firebase-functions'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-iid:21.1.0'
```

But it would be nice if the fix was implemented on the SDK itself.

**Comment by ColtonIdle** [comment]
Came here to report this. Simply updated BOM and got hit with this error. Thanks for the current workaround @thatfiredev

**Comment by KVAMALRAJ** [comment]
I am facing same issue, after updating FB Bom to 31.0.1

**Comment by mikehardy** [comment]
@KVAMALRAJ it was not resolved yet, 31.0.1 only contained a fix to crashlytics crash bug. That's why this issue is still open. The team here will make a fix *close* the issue, then do a release likely with release notes indicating it is fixed, when it is fixed https://firebase.google.com/support/release-notes/android - here

**Comment by ColtonIdle** [comment]
This does not seem to be fixed in 31.0.2. Will provide more details in a few, but I just updated and I have the same issue.

**Comment by ColtonIdle** [comment]
```
Duplicate class com.google.firebase.iid.FirebaseInstanceIdReceiver found in modules firebase-iid-20.0.1-runtime (com.google.firebase:firebase-iid:20.0.1) and firebase-messaging-23.1.0-runtime (com.google.firebase:firebase-messaging:23.1.0)
```

Using latest 31.0.2. Lets see if the previous workaround fixes the issue here too

**Comment by ColtonIdle** [comment]
If I add

  implementation("com.google.firebase:firebase-iid:21.1.0")

then were good

**Comment by mikehardy** [comment]
@ColtonIdle the issue was fixed but the commit is untagged / has not been released yet: https://github.com/firebase/firebase-android-sdk/commit/d939e6343e0b4a0f63311107dd3c304d0a6a1b8f - so I think you should still expect to see the error + need the workaround

**Comment by ColtonIdle** [comment]
oooh. i read the above message as "its fixed in 31.0.2". sounds good. looking forward to trying out the fix soon

**Comment by TrustyTechSG** [comment]
Is 31.0.3 fixed this? we also have this issue on Expo cloud build on 31.0.2([react-native-firebase][16.4.3])

**Comment by mikehardy** [comment]
@TrustyTechSG still showing as "unreleased" when I look: https://github.com/firebase/firebase-android-sdk/blob/master/firebase-functions/CHANGELOG.md#unreleased

And I don't see functions as part of the 31.0.3 release https://firebase.google.com/support/release-notes/android

So I do not think it has been released. 

I am the maintainer of react-native-firebase and I think we have a workaround in place in the repository such that this should not actually affect any react-native-firebase users https://github.com/invertase/react-native-firebase/blob/main/packages/messaging/android/build.gradle#L120

If you have a problem please open it in react-native-firebase repository issues list providing full details and we can attend to it

**Comment by TrustyTechSG** [comment]
> @TrustyTechSG still showing as "unreleased" when I look: https://github.com/firebase/firebase-android-sdk/blob/master/firebase-functions/CHANGELOG.md#unreleased
> 
> And I don't see functions as part of the 31.0.3 release https://firebase.google.com/support/release-notes/android
> 
> So I do not think it has been released.
> 
> I am the maintainer of react-native-firebase and I think we have a workaround in place in the repository such that this should not actually affect any react-native-firebase users https://github.com/invertase/react-native-firebase/blob/main/packages/messaging/android/build.gradle#L120
> 
> If you have a problem please open it in react-native-firebase repository issues list providing full details and we can attend to it

Thank you Mike

**Comment by svenjacobs** [comment]
It seems this was fixed in version `20.2.1` of `firebase-functions` which is also part of [Firebase BOM](https://firebase.google.com/docs/android/learn-more#bom) `31.1.0`.

**Comment by rlazo** [comment]
@svenjacobs @TrustyTechSG yes, the latest version of `functions` should fix this issue. Please let us know if it doesn't!

**Comment by svenjacobs** [comment]
Yes, `20.2.1` fixes it for me. Many thanks 👍🏼
