### ISSUE TITLE
Firestore is not picking up fresh auth token and reinitialising event listeners when the current token is stale.

### ISSUE THREAD

**Issue by russellwheatley** [firebase/firebase-android-sdk#5101]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Flamingo | 2022.2.1 Patch 2
  * Firebase Component: _____ Firestore, Auth
  * Component version: Android BOM 32.0.0

### [REQUIRED] Step 3: Describe the problem

We have this issue on the FlutterFire repository: https://github.com/firebase/flutterfire/issues/11146
There's also an active SO issue here: https://stackoverflow.com/questions/76436462/firebase-logged-in-user-with-expired-auth-id-token?noredirect=1

To summarise:

1. The user logs in via Auth SDK. Firestore snapshot event listeners are attached.
2. The app goes into the background for a lengthy period of time (in the range of 5-10 hours).
3. Whilst the user is still logged in, the event listeners start firing exceptions with "permission-denied" exceptions. 
4. The user has to reattach the Firestore snapshot listeners to make use of the fresh auth token.

My understanding and after discussion with @puf,  Firestore ought to pick up the fresh auth token under the hood, and reattach the snapshot event listeners without the user having to do this step manually.

#### Steps to reproduce:

Not an easy one to reproduce as it requires a lengthy time period, but following on from the summary:

1. Implement Firestore event listener that requires level of auth access via Firestore rules.
2. Log user in via Auth with access to the data being listened to.
3. Put app in background for >= 10 hours (Might be worth just letting it run for the day and coming back to it.)
4. Bring app to foreground, add data to that aspect of data being listened to on snapshot listener, and wait for a `permission-denied` error via logcat.

The user mentioned in the FlutterFire issue that the problem occurs when the app is brought to the foreground but I have asked for confirmation whether it occurs when the app is also in a background state as I suspect it does. This would remove the variable of app state from the reproduction.

#### Relevant Code:

Create a barebones app on android studio and implement simple Auth login with Firestore event listener following steps mentioned above.

**Comment by MarkDuckworth** [comment]
@russellwheatley, I'll work on a reproduction and see if we can get this fixed.

**Comment by RamsayGit** [comment]
The [initial problem](https://youtube.com/shorts/Fq67pKY0yDo?feature=share) I faced was that after resuming the app after an extended period (a day or two), all long-lived snapshots would stop updating, even though new reads and writes would still go through. I managed to apply a temporary patch to the issue by recreating all snapshot listeners when the app resumes. The following is an example of how this was done:
```
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      _attachListener();
    }
  }

  void _attachListener() {
    _hangoutSubscription?.cancel();
    _hangoutSubscription = FirebaseFirestore.instance
        .collection(FirePath.hangouts)
        .where....
        .snapshots(includeMetadataChanges: true)
        .transform(ignorePermissionDeniedTransformer())
        .listen((snapshot) {
          ...
        }, onError: (error) {
          FirebaseCrashlytics.instance.recordError(
            error,
            StackTrace.current,
            reason: 'Error in AdminHangoutRepository',
          );
        });
  }
}
```
This solution seemed to fix the issue in production for a few days, but today a new variant of the problem appeared. This time, the issue seems to be that the token didn't refresh, and yet the user remained logged in. I have this code in place to log out the user, but it didn't trigger:
```
_authStateSubscription =
    FirebaseAuth.instance.authStateChanges().listen((user) {
  if (user == null) {
    set(RouteState.login()); //did not fire when auth id token expired
  }
});
```
As shown in [this video](https://youtube.com/shorts/MZ1hbLlZu7k?feature=share) I captured from my production app today, nothing updates in response to my read and write requests. Connecting my phone to logcat indeed showed permission errors:
```
 16:29:15.551 19076 Firestore        com.letshang.app        W  (24.6.0) [z0]: (74f4cfa) Stream closed with status: j1{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}.
16:29:15.564 19076 Firestore        com.letshang.app        W  (24.6.0) [Firestore]: Write failed at users_private/JDGWvPLVtNTcrb: j1{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}
16:46:09.985 19076 Firestore        com.letshang.app        W  (24.6.0) [Firestore]: Listen for Query(target=Query(hangouts where statein[pre_open,open] order by geohash_6, __name__);limitType=LIMIT_TO_FIRST) failed: j1{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}
```
Despite these permission errors, the user remains logged in and authStateChanges doesn't get called. I'm currently unsure how to patch this until Firebase addresses this fundamental issue. A potential workaround could be calling user.getIdTokenResult() on each app resume, or perhaps performing a single write every few hours on app resume to check for the permission denied error, and then automatically log out the user if it's encountered.

Please let me know if there are any potential issues with my approach to detecting when the user should be logged out, or if you have found a more effective temporary workaround for this issue.

**Comment by puf** [comment]
Thanks for the additional info @RamsayGit. Most helpful, and appreciated. 🙏

> A potential workaround could be calling `user.getIdTokenResult()` on each app resume
My fear is that your `getIdTokenResult` will only happen after the connections to Firestore are already restored - and thus the listeners cancelled due to not meeting the requirement of the rules. So the full workaround would then require you to also re-attach the listeners. Totally fine for a workaround, but I hope Mark can reproduce the issue and find the root cause.

**Comment by RamsayGit** [comment]
In my most recent Android app release, I've introduced code that detects the 'Permission Denied' error upon app resume and prompts the user to re-login to rectify the situation. While this solution initially seemed effective, I discovered it does not work consistently; completely restarting the app proves to be a more reliable solution.

To summarize the various instances in which this error occurs:

1. The issue appears to be exclusive to Android.
2. Implementing token refresh and recreating snapshot listeners has alleviated the severity of the error, yet it persists.
3. On occasions when solution number 2 fails, the token is invalidated across the entire app. Re-logging in only occasionally resolves this; more often, a complete app restart is necessary. Notably, Firebase maintains the user login throughout these episodes.
4. This is a significant, foundational bug that effectively incapacitates Firebase for Flutter on Android. I would strongly recommend Google to halt further Firebase development and concentrate on rectifying this core issue. This affects every user of Firebase and Flutter on Android.

[Here's a video demonstrating the error occurring twice recently, where the only effective solution was to restart the app.](https://youtube.com/shorts/8utcxVIbDXk?feature=share)

![image](https://github.com/firebase/firebase-android-sdk/assets/3251763/11b3f209-4406-47fe-8c3e-ede120508255)

**Comment by MarkDuckworth** [comment]
I attempted to reproduce this week with my own app, but did not have success. I'm tweaking some things and continuing to try.

Can you tell me if this is only happening on a specific device or is this happening for many users of your app? Have you seen the issue on an emulator?

> Despite these permission errors, the user remains logged in and authStateChanges doesn't get called.

I'm curious if `idTokenChanges` would trigger for this event. Have you tried using this?

> On occasions when solution number 2 fails, the token is invalidated across the entire app. Re-logging in only occasionally resolves this; more often, a complete app restart is necessary. Notably, Firebase maintains the user login throughout these episodes.

Can you tell me more about this? How are you implementing this re-logging in? Can you go into more detail about "Firebase maintains the user login throughout these episodes"? Are other Firebase services also affected in this scenario?

Would you be willing to share more context from the Firestore SDK logs? Specifically include in the logs from the time period when the app fails to refresh the token, or when you believe that happens. If you want to share those logs securely, you can [create a support case](https://firebase.google.com/support/troubleshooter/contact), where you can reference this ticket and share logs.

I'm not available to work on this issue next week but will pick it up after. CC'ing @prameshj and @ehsannas  for visibility.

**Comment by RamsayGit** [comment]
> I attempted to reproduce this week with my own app, but did not have success. I'm tweaking some things and continuing to try.

To recreate it in a minimal way, I would consider an app with two pages: a login page and a time display page. The app should allow users to log in via Google, then navigate to the time display page. On this page, a snapshot listener should be set up to monitor updates to a Firestore document. This document should have a time field that is updated every minute by a cloud function and is protected by security rules that require a user token to access (request.auth != null). The app should be programmed to listen for null Firebase auth user events to automatically return to the login page when a user logs out. Once the app is built into a release APK and installed on a phone, the issue can be replicated by repeatedly bringing the app from the background state to the foreground every few hours to check if the time displayed updates upon app resume. Within a few days at most (often within a single day), you should come across the error when you notice the time no longer updates upon resuming the app, despite the user remaining logged in (the user remains in the time display page).

> Can you tell me if this is only happening on a specific device or is this happening for many users of your app? Have you seen the issue on an emulator?

The issue is not specific to a single device but occurs across various Android devices. This has been verified through Crashlytics.

> I'm curious if idTokenChanges would trigger for this event. Have you tried using this?

Regarding the use of idTokenChanges, this approach was not adopted because at the time of implementation, it seemed more straightforward to monitor user auth events to ascertain if a user is logged in or not.

> Can you tell me more about this? 

There is 2 variants of this problem:
1- The snapshot listener ceases to receive updates, resulting in stale data, without producing any errors. I believe I've managed to resolve this by refreshing the token when the app resumes and then re-creating all long lived snapshot listeners. This allows the app to function normally.
2- Sometimes, upon re-creating the listeners, I encounter a 'permission denied' exception. This affects all operations across the app, effectively crippling its functionality. Despite this, the user stays logged in (Firebase user auth is not null). In these instances, I advise the user to attempt re-logging in or to restart the app if the problem persists, as illustrated in [this video](https://www.youtube.com/shorts/8utcxVIbDXk).

> How are you implementing this re-logging in?

When the app detects an error, a prompt notifies the user and guides them to manually log out and log back in. This sequence is depicted in [the video](https://www.youtube.com/shorts/8utcxVIbDXk). Logging out is accomplished with a simple call to FirebaseAuth.instance.signOut() and my router automatically sends the user back to the login screen. Although this usually works, it does not always rectify the problem, as the video demonstrates. In such cases, restarting the app is the most reliable solution.

> Can you go into more detail about "Firebase maintains the user login throughout these episodes"?

When I say "Firebase maintains the user login throughout these episodes," I mean that at no point is the user automatically logged out. Despite the token seemingly being invalid—as evidenced by the snapshot listeners throwing 'permission denied' errors—the user stays logged in, as demonstrated in the video. The Firebase logout detection code never activates:
```
    _authStateSubscription =
        FirebaseAuth.instance.authStateChanges().listen((user) {
      if (user == null) {
        set(RouteState.login());
      }
    });
```

> Are other Firebase services also affected in this scenario?

I can't confirm whether they are affected, as Firestore is used in 99% of the operations within my app.

> Would you be willing to share more context from the Firestore SDK logs?

The logs predominantly contain 'permission denied' errors without further significant information. Here's an instance from Crashlytics:
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:652)
       at MethodChannel._invokeMethod(platform_channel.dart:310)
       at MethodChannelDocumentReference.set(method_channel_document_reference.dart:32)
```

**Comment by MarkDuckworth** [comment]
I attempted to reproduce again this week, this time with a release build of my app. The app has been running most of the week and I have not been able to reproduce the issue. Testing included letting the app run in the background overnight several times, running the app in the bg and opening it every few hours through the day. I also tested changing networks during the bg period and leaving the phone offline for multiple hours.

@russellwheatley, did you reproduce the issue as well? Have either of you reproduced with the firebase-android-sdk or only with the Flutter SDK in a Flutter app? If so, can you provide that reproduction?

For what it's worth, we did some analysis to see if there is a higher rate of PERMISSION_DENIED or UNAUTHORIZED errors from the Android clients. This would indicate that there is a token refresh issue for the Android SDK affecting many apps. We did not see evidence of that in our analysis.

**Comment by RamsayGit** [comment]
I will start working on a reproduction this week. In my live app I had to resort to measures such as extending the token lifetime significantly alongside code hacks I already implemented such as recreating all snapshots on app resume and still it remains by far the most reported error in Crashlytics in Android and to a lesser extend iOS.

**Comment by russellwheatley** [comment]
Thanks for the investigation, @MarkDuckworth. I have not recreated this issue. Happy to investigate the reproduction @RamsayGit creates 👍

**Comment by RamsayGit** [comment]
@russellwheatley @puf @MarkDuckworth  **Here it is:**
![Screenshot_small](https://github.com/firebase/firebase-android-sdk/assets/3251763/49c4fc4a-4c3e-4fef-b0ac-60fee7049ef7)

I've created a Minimal, Complete, and Verifiable Example (MCVE), and within four hours of launching the app (in release mode with Play Integrity App Check APK on device), the snapshot listener ceased functioning due to a permission error, as shown. It's no longer tracking the cloud-updated time value.

The MCVE contains several API keys, and the project is associated with a paid Blaze plan, as cloud functions weren't compatible with the Spark plan. Could you please guide me on securely sharing this project with you, and suggest measures to ensure I don't incur charges for this project?

**Comment by MarkDuckworth** [comment]
That's great news! Can you share the source as a github repo and remove your keys? A private repo works. I can configure it to run against one of our test projects.

**Comment by RamsayGit** [comment]
I've created a repo and sent you an invitation. A significant part of the setup needed to recreate the error resides within the Firebase project, not the code. I will highlight the most crucial elements:

1- App Check must be enforced for Firestore with Play Integrity, and the token refresh set to the minimum of 30 minutes.
2- Google Sign-In needs to be enabled.
3- The Firestore security rules should be set up as follows:
```
rules_version = '2';

service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow list: if request.auth != null 
      	&& request.auth.token.firebase.sign_in_provider == 'google.com'
        && request.query.limit <= 5;
    }
  }
}
```
4- The Storage security rules should be set up as follows:
```
rules_version = '2';

service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
  }
}
```
5- Firestore should be set up as displayed in the image:
![image](https://github.com/firebase/firebase-android-sdk/assets/3251763/e4a5374c-dad8-4d6d-a751-f5f0e0479dbf)

6- Deploy the cloud function that continuously updates the time field.
7- Build the app into a release APK, deploy it to a physical device, and periodically resume it from the background.

**Comment by MarkDuckworth** [comment]
I didn't realize this involves App Check. When you say, "App Check must be enforced for Firestore with Play Integrity", does that mean you only see this when using app check?

**Comment by RamsayGit** [comment]
> I didn't realize this involves App Check. When you say, "App Check must be enforced for Firestore with Play Integrity", does that mean you only see this when using app check?

I never tried without App Check so I cannot comment on that. This is a stripped down version of my actual released project in terms of Firebase setup. I didn't ever think of not enabling app check since it felt like a necessary security measure.

**Comment by RamsayGit** [comment]
@MarkDuckworth Can I please be informed of the current status of this issue?

**Comment by MarkDuckworth** [comment]
Hi @RamsayGit, once I added App Check to my own Android app built with the Firebase Android SDK, I started producing a similar behavior, though in my case logging in again seemed to solve the problem consistently. I do believe this is related to app check, and I have shared it with that team. However I do intend to take another look in the next week to see if I can move it forward.

Not sure if it will be useful to you at this point, but there is an API to listen for [AppCheck token state changes](https://pub.dev/documentation/firebase_app_check/latest/firebase_app_check/FirebaseAppCheck/onTokenChange.html).

**Comment by RamsayGit** [comment]
@MarkDuckworth After further testing with the MCVE project I'm almost certain the issue is directly related to Appcheck since I could not replicate the error with Appcheck turned off. When do you anticipate this issue to be resolved? it remains the most reported bug affecting users daily and I'm wondering if it is acceptable to turn Appcheck off and rely on security rules alone?

**Comment by MarkDuckworth** [comment]
@RamsayGit can you share your Flutter MCVE with me again, I lost access to the repo?

I spent some time digging into this issue again this week and what I was seeing in my Android Java app may have been a red herring. I was experiencing my activity being destroyed and re-created after being in the background for a while. After re-creation the listeners were not correctly restarted. It's unclear why I initially started seeing that when I enabled app check.

Regardless, based on the described behavior and what you tested above, I still feel that this is related to app check. It may also be specific to Flutter and the Flutter lifecycle. I'm not a Flutter dev, so I could use some help from @russellwheatley.

> I'm wondering if it is acceptable to turn Appcheck off and rely on security rules alone?

I think that's a question only your team can answer.


Additional thoughts:
- When reviewing the app check token logic in Android Firebase, failure to refresh should be logged. Do you see any error messages like "Firebase AppCheck API not available" or "Failed to get AppCheck token"?
- Regarding a workaround. When you detect this scenario, have you considered using the [getToken](https://pub.dev/documentation/firebase_app_check/latest/firebase_app_check/FirebaseAppCheck/getToken.html) method to force and app check token refresh?

**Comment by MarkDuckworth** [comment]
@russellwheatley, We've reviewed this and can't find a repro on native Android. I've chatted with several adjacent teams from Firebase Android and App Check, and it seems like the next step is to see if you can get any additional information from the customer's FlutterFire MCVE. Can you test the MCVE and see if you can provide the full Firebase log output from the app? Also, the AppCheck team wanted to ensure that the issue occurs when Auth is disabled and AppCheck is enabled, is that something you can test?

**Comment by russellwheatley** [comment]
Hey @MarkDuckworth, sorry for late response. I can take a look at the FlutterFire MCVE and see what I find 👍

**Comment by russellwheatley** [comment]
@RamsayGit - my invitation to the repo has expired, do you mind reinviting me, please?

**Comment by RamsayGit** [comment]
> @RamsayGit - my invitation to the repo has expired, do you mind reinviting me, please?

Invitation has been sent.

**Comment by gmarizy** [comment]
I experience the same error, on Android and iOS alike, and I use app check too. 

This error might be related: https://github.com/firebase/flutterfire/issues/11491

In our app, we display a retry button when Firestore snapshot stream fail. Some people reported to me that when the problem occur, they must press the retry button several times before having data. My uneducated guess is that app check token renew might fail (see linked issue) or be too slow, triggering a timeout in Firestore client or something like that.

**Comment by RamsayGit** [comment]
@gmarizy @russellwheatley Yes the bug is due to App Check and the only way I could get rid of it is by disabling App Check. I submitted a reproduction to the Firebase team 2 months ago and I'm awaiting an update from them.

**Comment by russellwheatley** [comment]
@RamsayGit - as a small update, I have the app running since yesterday on my android device with App Check enforced. No error as yet. I will keep it running until over the next few days in the hope I see the error.

I am curious about the Storage rules. There isn't any Storage plugin usage, and I presume you use Storage as part of your app and not part of the MCVE.

**Comment by gmarizy** [comment]
Mine:
```
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow write: if request.auth != null;
      allow read: if true;
    }
  }
}
```

And I don't enforce App Check for storage.

**Comment by gmarizy** [comment]
I just noticed that I have some "Unverified requests" on App Check reports concerning Firestore. App check is enforced for Firestore, so I guess those unverified request correspond to the `[cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.` errors. 

Just a wild guess: when app is in background, under unknown circumstances App Check token is not renewed. When app is resumed, active snapshots listening trigger calls to Firestore but without App Check token attached, since there is no valid one available.

**Comment by russellwheatley** [comment]
> I just noticed that I have some "Unverified requests" on App Check reports concerning Firestore. App check is enforced for Firestore, so I guess those unverified request correspond to the [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation. errors.

FYI; I have observed unverified requests without triggering the "permission denied" exception.

> Just a wild guess: when app is in background, under unknown circumstances App Check token is not renewed. When app is resumed, active snapshots listening trigger calls to Firestore but without App Check token attached, since there is no valid one available.

This seems likely to me. A permission denied response seems to be a result of a stale token. Particularly as @RamsayGit mentioned this does not occur once App Check is deactivated.

**Comment by gmarizy** [comment]
I guess App check token is attached to Firestore request alongside Firebase Auth token. But there seems to be no problem with Auth token renewal whereas we encounter some with App Check token renewal. So Firestore handle (wait) Auth token renewal but not App Check token renewal ? From time to time App Check token renewal could took too long and Firestore auto-retry end with a timeout. We can't also rule out that App Check renewal just fail (related to https://github.com/firebase/flutterfire/issues/11491).

**Comment by RamsayGit** [comment]
> @RamsayGit - as a small update, I have the app running since yesterday on my android device with App Check enforced. No error as yet. I will keep it running until over the next few days in the hope I see the error.
> 
> I am curious about the Storage rules. There isn't any Storage plugin usage, and I presume you use Storage as part of your app and not part of the MCVE.

@MarkDuckworth Thank you for the update. The error typically appears within a day or two if all steps in the MCVE Github readme are applied including security rules. 
The Storage rules can be ignored, I think I put them in for completeness.

**Comment by gmarizy** [comment]
Hello @russellwheatley, do you have any news regarding the issue ?

**Comment by russellwheatley** [comment]
Hi, there. We're reasonably sure we've identified what is causing the issue. It seems there is a difficulty translating the suspected API to a pure android reproducible implementation which would allow the issue to be resolved. Bear with us, we haven't given up, it's a rather difficult one to fix given the time frame the error may appear. The last time I reproduced the bug, it took 3 days for the error to appear. Thank you for your patience 🙏

**Comment by schuey06** [comment]
Hi @russellwheatley  thanks for your efforts on this. I'm seeing similar PERMISSION_DENIED issues with my android firestore client app, with AppCheck enabled/enforced. Many of my users operate for long periods of time offline. The issue occurs after long periods of inactivity/backgrounded app as you found. This is also my number 1 issue. Keen to find a fix for this.  Thanks again

**Comment by russellwheatley** [comment]
@schuey06 - is this with a flutter android app or a pure android app?

**Comment by schuey06** [comment]
Hi @russellwheatley this is a native kotlin/compose android app

**Comment by russellwheatley** [comment]
@schuey06 - Do you mind sharing a small reproducible code sample? The reason it has taken s long getting this fixed is translating the Flutter reproducible bug into a pure android implementation. It would really help the android team get this resolved.

**Comment by offline-first** [comment]
Some users (250 of 45k) in the last 30 days have the same issue when writing to Firestore with batch commit after login. The problem is on both platforms, iOS and Android (Flutter).

**Comment by nialljawad96** [comment]
Any update on this? Since this is the issue most likely:

> Just a wild guess: when app is in background, under unknown circumstances App Check token is not renewed. When app is resumed, active snapshots listening trigger calls to Firestore but without App Check token attached, since there is no valid one available.

Is there a way to mitigate against this until a fix is available? For example, using a onResume to manually refresh/fetch the new token?

**Comment by ramsayamarin** [comment]
> Any update on this? Since this is the issue most likely:
> 
> > Just a wild guess: when app is in background, under unknown circumstances App Check token is not renewed. When app is resumed, active snapshots listening trigger calls to Firestore but without App Check token attached, since there is no valid one available.
> 
> Is there a way to mitigate against this until a fix is available? For example, using a onResume to manually refresh/fetch the new token?

There is not. I initially did all sorts of hacks and it definitely decreased the incidence rate but ultimately it still happened and the only way to completely resolve it is to disable app check until a solution is provided.

**Comment by casumatt** [comment]
Hi, I am just flagging that this is a consistant issue for us. Ours is similar but not a listener. It is an 'add' document call on AppResume. AppCheck is turned off. Security rules allow full create on the collection. The error does not display in normal development, but when the app is placed into the background for a while (the timeframes seem to differ, but a few hours will do it), then we reopen and we get the " [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation". All these calls go through successfully if the app is placed into the background and resumed quite quickly. I'm interested in a workaround or resolution, and also with some advice, for testing purposes can someone set auth token expiry to a super short timeframe so that reproducing and debugging doesn't take as long?

**Comment by dconeybe** [comment]
For anyone who is able to reproduce this issue, debug logs leading up to the permission denied and/or unauthenticated error would be incredibly helpful. Please enable debug logging and reproduce and capture the logcat immediately after reproducing the exception.

Notably, Android has interesting application lifecycles so it's unclear if (a) the activity/service was destroyed and re-created when the user navigates back to the app of if (b) the entire process was killed and recreated from scratch when the user navigates back to the app. The logs will help ascertain this behavior and hopefully guide creation of a consistently-reproduce scenario. 

You may want to increase the logcat buffer size on your device, given the amount of time that elapses when attempting to reproduce (see screenshot below). Also, you may want to experiment with "Don't keep activities" and "Background process limit" to see if either of these settings make the problem easier to reproduce (see screenshots below).

![Screenshot of Logger buffer sizes in Android Developer Options](https://github.com/firebase/firebase-android-sdk/assets/61283819/3e4dd8c9-4260-4257-8bf7-316a45a86d0f)
![Screenshot of setting Logger buffer sizes to the maximum value in Android Developer Options](https://github.com/firebase/firebase-android-sdk/assets/61283819/2a99a57d-9a6a-4ae4-87b6-c62563c6c26b)
![Screenshot of Don't keep activities and Background process limit in Android Developer Options](https://github.com/firebase/firebase-android-sdk/assets/61283819/34b7918a-d2fa-4a64-b780-7fff825fab43)

**Comment by dconeybe** [comment]
Could anyone experiencing this issue please try to reproduce as follows:

1. Start the application in the Android emulator inside Android Studio; its Firestore requests should succeed.
2. Pause the Android emulator by pressing the "Stop" button in the "Device Manager" window.
3. Wait for a few hours.
4. Resume the Android emulator by pressing the "Play" button in the "Device Manager" window.
5. Observe if the Firestore requests succeed after resuming the Android emulator.

When the "Stop" button is pressed, the entire state of the emulator is saved. Later, when "Play" is pressed, it resumes the emulator from right where it left off. If the emulator has been paused for enough time that the Auth and/or AppCheck tokens have expired then Firestore will try to reconnect with the expired tokens. This _may_ be an easy way to reproduce the bug consistently.

**Comment by anilthapa1939** [comment]
any update on this?

**Comment by dconeybe** [comment]
> any update on this?

The investigation is stalled. We are waiting for logs and/or a reproducible scenario in order to continue investigation.

**Comment by ramsayamarin** [comment]
@dconeybe I did create a reproduction and provided a year ago and @russellwheatley did confirm the reproduction. It has been a while so maybe I missed something but just wanted to let you know about it in case it got lost.

**Comment by dconeybe** [comment]
@ramsayamarin Could you re-invite me and @MarkDuckworth to your repro app: https://github.com/RamsayGit/firebase-token-refresh-mcve.

**Comment by dconeybe** [comment]
Oh I see you've invited me. I'll take a look this week. Thank you.

**Comment by princ3od** [comment]
Today I think I've encountered a similar bug caused by this issue.
My sign-up function looks like this:

```js
const signUp = async ({ email, password, ... }: SignUpProps) => {
  const userCredential = await createUserWithEmailAndPassword(
    auth,
    email,
    password
  )
  const firebaseUser = userCredential.user

  try {
    const newUserRef = doc(firestore, "users", firebaseUser.email!)
    await setDoc(
      newUserRef,
      {
        email: firebaseUser.email,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        // ...
      },
      { merge: true }
    )

  //...

    return {
      id: firebaseUser.email!,
      email: firebaseUser.email,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      // ...
    } as AppUser
  } catch (e) {
    await firebaseUser.delete()
    throw new Error("Failed to create user")
  }
}
``` 

My users have recently reported that they could not sign up. I tried debugging and found out that the `setDoc` function keeps raising error `FirebaseError: Missing or insufficient permissions`. This sign-up function has worked perfectly and the Firestore rules have not been changed as well. 

So I think Firestore might've used an old auth token, I try to force Firestore to create a new token right before calling the `setDoc` function by adding `await firebaseUser.getIdToken(true)`

```js
const signUp = async ({ email, password, ... }: SignUpProps) => {
  const userCredential = await createUserWithEmailAndPassword(
    auth,
    email,
    password
  )
  const firebaseUser = userCredential.user

  // Force refresh the auth token
  await firebaseUser.getIdToken(true)

  try {
    const newUserRef = doc(firestore, "users", firebaseUser.email!)
    await setDoc(
      newUserRef,
      {
        email: firebaseUser.email,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        // ...
      },
      { merge: true }
    )

  //...
}
``` 
Surprisingly, the bug is gone, and my users now can sign up normally.

**Comment by eli1stark** [comment]
@dconeybe

We've been experiencing this issue with our app as well, which has unfortunately prevented us from using Firebase App Check on Android for the past 2 years. I understand this is likely a complex issue to resolve, and I truly appreciate the effort you and your team have put into investigating it.

Given the extended timeline and the impact on production apps, I was wondering if there might be any updates on the progress or potential workarounds we could explore?

If this issue proves particularly challenging to resolve in the near term, would it be helpful to add a note in the Firebase documentation? This could help other developers who might encounter similar difficulties, saving them debugging time while a permanent solution is being developed. Additionally, if a fix isn't feasible, transparently marking it as such would help teams make informed decisions about their app security strategies.

**Comment by eli1stark** [comment]
@dconeybe Are there any updates on this issue? It's been almost a year since the last comment, so I wanted to check whether you are marking this issue as non-fix.

**Comment by dconeybe** [comment]
Ahh dang sorry all. This issue slipped off my radar. I'll spend some time on it soon, but can't make any concrete promises at the moment.

**Comment by zafarivaev** [comment]
Hey, I’ve had a similar issue on iOS. For some reason, Firestore Rules consistently showed a fixed number of denies every hour. I spent days researching the problem but couldn’t find a viable solution. I am not even using App Check. Users would just occasionally get logged out, and since my Firestore rules rely on `request.auth != null`, those requests would fail.

However, it seems like something changed or was fixed today. I have not had a single deny since, so hopefully the issue has been resolved.

**Comment by eli1stark** [comment]
@zafarivaev It looks like you might be dealing with a different issue.

**Comment by zafarivaev** [comment]
@eli1stark I thought the issue was similar because the reproduction steps are the same: a user is logged in, then puts the app in the background for some time, and upon reopening it, receives a permission-denied error on Firestore listeners. What’s interesting is that this does not happen consistently. It affects a portion of the user base intermittently and forces them to log back in.

**Comment by deme87** [comment]
Hey I have a similar issue with AppCheck. This happens occasionally and it seems that is related to AppCheck since when i unenforce it i stop getting [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
This causes all my listeners to detach and i had to manually restart them.

Are there any updates on this?

**Comment by deme87** [comment]
Any updates on this?
