### ISSUE TITLE
Firebase Performance Monitoring: The App start trace `_app_start` seems missing, but other traces work!

### ISSUE THREAD

**Issue by kurosaki-tisak** [firebase/firebase-android-sdk#5764]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Hedgehog | 2023.1.1 Patch 2
  * Firebase Component: Firebase Performance
  * Component version: com.google.firebase.firebase-perf:1.4.2

#### Steps to reproduce:

As the screenshot below, I found the app start trace was missing from both the Logcat and Performance dashboards, but other automatic traces and custom traces work! 

<img width="1357" alt="Screenshot 2567-03-07 at 08 49 55" src="https://github.com/firebase/firebase-android-sdk/assets/25000465/3d2083e5-7d95-46be-9977-77814855a266">

I have done everything like the [documents](https://firebase.google.com/docs/perf-mon/troubleshooting?platform=android#app-not-logging-events)  said, but the `_app_start` is still missing!

**Comment by lehcar09** [comment]
Hi @kurosaki-tisak, thank you for reaching out and reporting the issue. When trying to reproduce the issue, I noticed that instead of "_app_start", an "_as" event has been logged in the Logcat.

![Screenshot 2024-03-12 at 10 21 02 PM](https://github.com/firebase/firebase-android-sdk/assets/155964350/3764822e-38ce-4408-a6ca-7dbdb9aacdf3)

Upon checking the Firebase Console Dashboard, the "_app_start" event is visible under the Custom traces tab.

![7pxfCc2HzW5cGup](https://github.com/firebase/firebase-android-sdk/assets/155964350/54c5335f-6e6c-4201-861f-97e7f816c2a3)

Could you check if you can see the `_as` event being logged?

**Comment by kurosaki-tisak** [comment]
Hello @lehcar09 and thank you for your support!

As you can see in the screenshot below, `_as` trace seems missing while both `_fs` (_app_in_foreground) and `_bs` (_app_in_background) work as usual!

![Screenshot 2567-03-13 at 09 44 45](https://github.com/firebase/firebase-android-sdk/assets/25000465/842966f4-d5a1-4496-ba56-648a22a3e9bb)

Also, on the Firebase Performance Dashboard, as shown in the screenshot below, the _`app_startup` (showing only 1 sample) used to appear long ago. Now, as I've mentioned, it's missing without any clue, so please help! 

<img width="1069" alt="Screenshot 2567-03-13 at 11 19 50" src="https://github.com/firebase/firebase-android-sdk/assets/25000465/f371fbab-b925-4610-bb68-ae71f380de6e">

Thank you!

**Comment by lehcar09** [comment]
Is there any chance you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to help us investigate the issue? If you're unable to provide one, can you try our [quickstart app](https://github.com/firebase/quickstart-android/tree/master) and see if you can reproduce the issue?

**Comment by VishalRajora** [comment]
I am also facing the same issue.
After changing BOM version from  '31.1.1' to above,  `_as` is not logged in the logcat and FirebasePerformance consol.

But the twist is, I have created one sample app and tried the same, So `_as` is logging in logcat and consol

**Comment by VishalRajoraTiket** [comment]
I have fixed this.

**Comment by argzdev** [comment]
Hi @VishalRajora, thanks for confirming that this is resolved on your end. I'm guessing there might've been a configuration issue. I'll go ahead and close this for now. Thanks!

**Comment by PhilGlass** [comment]
@argzdev we're seeing the same thing others have described above - no app start traces, but custom traces and all the other automatic traces are fine.

Looking at our data in Firebase this seems to have started when we upgraded the Firebase BOM from 31.1.1 to 32.2.0.

<img width="1394" alt="Screenshot 2024-05-01 at 13 10 35" src="https://github.com/firebase/firebase-android-sdk/assets/24500397/f14903a5-0728-45b1-874d-da3c652ddc93">

There are no `Firebase`-tagged errors in logcat that I can see, we just aren't getting any app start traces. How would you suggest I further debug this?

```
13:25:02.342 27812-27812 FirebaseApp             co.uk.getmondo.debug                 I  Device unlocked: initializing all Firebase APIs for app [DEFAULT]
13:25:02.421 27812-27812 FirebaseSessions        co.uk.getmondo.debug                 D  Initializing Firebase Sessions SDK.
13:25:02.423 27812-27812 FirebaseCrashlytics     co.uk.getmondo.debug                 I  Initializing Firebase Crashlytics 18.6.3 for co.uk.getmondo.debug
13:25:02.472 27812-27852 FirebaseCrashlytics     co.uk.getmondo.debug                 I  No version control information found
13:25:03.410 27812-27860 FirebasePerformance     co.uk.getmondo.debug                 I  Firebase Performance Monitoring is successfully initialized! In a minute, visit the Firebase console to view your data: https://console.firebase.google.com/project/monzo-android-staging/performance/app/android:co.uk.getmondo.debug/trends?utm_source=perf-android-sdk&utm_medium=android-ide
13:25:03.426 27812-27860 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: 'true' for key: 'fpr_enabled' from Firebase Remote Config.
13:25:03.427 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: 'true' for key: 'fpr_enabled' from Firebase Remote Config.
13:25:03.427 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '600' for key: 'fpr_rl_time_limit_sec' from Firebase Remote Config.
13:25:03.427 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '300' for key: 'fpr_rl_trace_event_count_fg' from Firebase Remote Config.
13:25:03.427 27812-27860 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '' for key: 'fpr_disabled_android_versions' from Firebase Remote Config.
13:25:03.428 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '' for key: 'fpr_disabled_android_versions' from Firebase Remote Config.
13:25:03.428 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '600' for key: 'fpr_rl_time_limit_sec' from Firebase Remote Config.
13:25:03.428 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '30' for key: 'fpr_rl_trace_event_count_bg' from Firebase Remote Config.
13:25:03.429 27812-27860 FirebasePerformance     co.uk.getmondo.debug                 D  Setting attribute 'type' to 'ApiThreatmetrixConfig' on trace 'moshi_response_deserialisation'
13:25:03.429 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '600' for key: 'fpr_rl_time_limit_sec' from Firebase Remote Config.
13:25:03.429 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '600' for key: 'fpr_rl_time_limit_sec' from Firebase Remote Config.
13:25:03.430 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '462' for key: 'fpr_log_source' from Firebase Remote Config.
13:25:03.436 27812-27860 FirebasePerformance     co.uk.getmondo.debug                 D  Setting attribute 'success' to 'true' on trace 'moshi_response_deserialisation'
13:25:03.444 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: 'true' for key: 'fpr_enabled' from Firebase Remote Config.
13:25:03.445 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: 'true' for key: 'fpr_enabled' from Firebase Remote Config.
13:25:03.445 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '' for key: 'fpr_disabled_android_versions' from Firebase Remote Config.
13:25:03.446 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '' for key: 'fpr_disabled_android_versions' from Firebase Remote Config.
13:25:03.446 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: 'true' for key: 'fpr_enabled' from Firebase Remote Config.
13:25:03.447 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '' for key: 'fpr_disabled_android_versions' from Firebase Remote Config.
13:25:03.450 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: 'true' for key: 'fpr_enabled' from Firebase Remote Config.
13:25:03.451 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '' for key: 'fpr_disabled_android_versions' from Firebase Remote Config.
13:25:03.452 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '1.0' for key: 'fpr_vc_trace_sampling_rate' from Firebase Remote Config.
13:25:03.455 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 I  Logging trace metric: moshi_response_deserialisation (duration: 8,111ms). In a minute, visit the Firebase console to view your data: https://console.firebase.google.com/project/monzo-android-staging/performance/app/android:co.uk.getmondo.debug/troubleshooting/trace/DURATION_TRACE/moshi_response_deserialisation?utm_source=perf-android-sdk&utm_medium=android-ide
13:25:03.518 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  FragmentMonitor WelcomeFragment.onFragmentResumed
13:25:03.521 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: 'true' for key: 'fpr_enabled' from Firebase Remote Config.
13:25:03.523 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '' for key: 'fpr_disabled_android_versions' from Firebase Remote Config.
13:25:03.525 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  Setting attribute 'Parent_fragment' to 'AutoLoginFragment' on trace '_st_WelcomeFragment'
13:25:03.528 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  Setting attribute 'Hosting_activity' to 'AutoLoginActivity' on trace '_st_WelcomeFragment'
13:25:03.533 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  FragmentMonitor AutoLoginFragment.onFragmentResumed
13:25:03.534 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: 'true' for key: 'fpr_enabled' from Firebase Remote Config.
13:25:03.540 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '' for key: 'fpr_disabled_android_versions' from Firebase Remote Config.
13:25:03.542 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  Setting attribute 'Parent_fragment' to 'No parent' on trace '_st_AutoLoginFragment'
13:25:03.544 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  Setting attribute 'Hosting_activity' to 'AutoLoginActivity' on trace '_st_AutoLoginFragment'
13:25:03.846 27812-27812 FirebasePerformance     co.uk.getmondo.debug                 D  Screen trace: _st_SplashActivity2 _fr_tot:0 _fr_slo:0 _fr_fzn:0
13:25:03.847 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: 'true' for key: 'fpr_enabled' from Firebase Remote Config.
13:25:03.847 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '' for key: 'fpr_disabled_android_versions' from Firebase Remote Config.
13:25:03.861 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: 'true' for key: 'fpr_enabled' from Firebase Remote Config.
13:25:03.861 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 D  Fetched value: '' for key: 'fpr_disabled_android_versions' from Firebase Remote Config.
13:25:03.861 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 W  non-positive totalFrames in screen trace _st_SplashActivity2
13:25:03.861 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 W  Invalid Trace:_st_SplashActivity2
13:25:03.866 27812-27978 FirebasePerformance     co.uk.getmondo.debug                 W  Unable to process the PerfMetric (trace metric: _st_SplashActivity2 (duration: 560,045ms)) due to missing or invalid values. See earlier log statements for additional information on the specific missing/invalid values.
```

**Comment by PhilGlass** [comment]
That turns out to only be the first issue - it still doesn't work after switching to `FirebaseInitProvider`.

When I attach a debugger and start the app from the launcher icon I'm seeing that this: https://github.com/firebase/firebase-android-sdk/blob/bb0823ffc999ccfc38d75a165f6c0391ed884f6b/firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java#L568-L572

is executed _before_ `onActivityCreated` is able to set `onCreateTime`: https://github.com/firebase/firebase-android-sdk/blob/bb0823ffc999ccfc38d75a165f6c0391ed884f6b/firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java#L328

So Firebase considers this a background process start and does not send an app start trace.

**Comment by PhilGlass** [comment]
The ordering assumptions described here seem to be wrong: https://github.com/firebase/firebase-android-sdk/blob/bb0823ffc999ccfc38d75a165f6c0391ed884f6b/firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java#L552-L559

Here's a simple demonstration that mimics what Firebase Performance is doing. Copy-paste this provider into a new sample project, register it in the manifest and launch the default activity:

```
class SampleProvider : ContentProvider() {
    private var activityCreated = false
    private var mainThreadRunnableRun = false

    override fun onCreate(): Boolean {
        (context!!.applicationContext as Application).registerActivityLifecycleCallbacks(object :
            ActivityLifecycleCallbacks {
            override fun onActivityCreated(activity: Activity, savedInstanceState: Bundle?) {
                Log.d(
                    "FirebasePerf",
                    "onActivityCreated: mainThreadRunnableRun = $mainThreadRunnableRun"
                )
                activityCreated = true
            }

            override fun onActivityStarted(activity: Activity) {}
            override fun onActivityResumed(activity: Activity) {}
            override fun onActivityPaused(activity: Activity) {}
            override fun onActivityStopped(activity: Activity) {}
            override fun onActivitySaveInstanceState(activity: Activity, outState: Bundle) {}
            override fun onActivityDestroyed(activity: Activity) {}
        })

        Handler(Looper.getMainLooper()).post {
            Log.d("FirebasePerf", "mainThreadRunnable.run(): activityCreated = $activityCreated")
            mainThreadRunnableRun = true
        }

        return true
    }

    override fun query(
        uri: Uri,
        projection: Array<out String>?,
        selection: String?,
        selectionArgs: Array<out String>?,
        sortOrder: String?
    ): Cursor? {
        TODO("Not yet implemented")
    }

    override fun getType(uri: Uri): String? {
        TODO("Not yet implemented")
    }

    override fun insert(uri: Uri, values: ContentValues?): Uri? {
        TODO("Not yet implemented")
    }

    override fun delete(uri: Uri, selection: String?, selectionArgs: Array<out String>?): Int {
        TODO("Not yet implemented")
    }

    override fun update(
        uri: Uri,
        values: ContentValues?,
        selection: String?,
        selectionArgs: Array<out String>?
    ): Int {
        TODO("Not yet implemented")
    }
}
```

You'll see this in logcat:

```
15:13:17.036 FirebasePerf              D  mainThreadRunnable.run(): activityCreated = false
15:13:17.352 FirebasePerf              D  onActivityCreated: mainThreadRunnableRun = true
```

**Comment by PhilGlass** [comment]
One more update: It appears that the ordering assumptions are correct on old versions of Android, but not newer versions. 

Using the sample code in https://github.com/firebase/firebase-android-sdk/issues/5764#issuecomment-2088534453:

API 24 (they are correct):

```
```
15:36:22.413 FirebasePerf              D  onActivityCreated: mainThreadRunnableRun = false
15:36:22.423 FirebasePerf              D  mainThreadRunnable.run(): activityCreated = true
```

API 34 (they are incorrect):

```
15:13:17.036 FirebasePerf              D  mainThreadRunnable.run(): activityCreated = false
15:13:17.352 FirebasePerf              D  onActivityCreated: mainThreadRunnableRun = true
```
