### ISSUE TITLE
SQLiteEventStore.lambda$ensureBeginTransaction$24: android.database.sqlite.SQLiteDatabaseLockedException - database is locked (code 5 SQLITE_BUSY)

### ISSUE THREAD

**Issue by lklong1551019** [firebase/firebase-android-sdk#6001]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Jellyfish | 2023.3.1 Patch 1
Build #AI-233.14808.21.2331.11842104, built on May 15, 2024
Runtime version: 17.0.10+0-17.0.10b1087.21-11572160 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON
Registry:
  ide.instant.shutdown=false
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  io.github.stefansjs.flatbuffersplugin (0.5+31)
  name.kropp.intellij.makefile (233.13135.65)

  * Firebase Component: com.google.gms:google-services:4.4.1,  com.google.firebase:firebase-crashlytics-gradle:2.9.9, org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.21, com.google.firebase:firebase-bom:32.8.0
  * Component version: org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.21

#### Steps to reproduce:

After updating firebase bom from 30.3.1 to 31.2.3 and now 32.8.0, for the past few months we have been experiencing random crashes (~ 400 crashes per day) on a variety of devices, across every android version, with 94% events happened while in background. It can happen when the app has just run for 10 seconds, or even for a long time. This crash starts to happen after: 

-  Updating bom from 30.3.1 to 31.2.3
-  com.google.firebase:firebase-crashlytics-gradle:2.9.0 to com.google.firebase:firebase-crashlytics-gradle:2.9.9
-  com.android.tools.build:gradle:4.2.2 to com.android.tools.build:gradle:8.2.0

We cannot reproduce this. Here is an example stack trace:

```
Fatal Exception: com.google.android.datatransport.runtime.synchronization.SynchronizationException
Timed out while trying to acquire the lock.
Fatal Exception: com.google.android.datatransport.runtime.synchronization.SynchronizationException: Timed out while trying to acquire the lock.
       at com.google.android.datatransport.runtime.synchronization.SynchronizationException.<init>(SynchronizationException.java:20)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.lambda$ensureBeginTransaction$25(SQLiteEventStore.java:759)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.retryIfDbLocked(SQLiteEventStore.java:585)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.ensureBeginTransaction(SQLiteEventStore.java:753)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.runCriticalSection(SQLiteEventStore.java:766)
       at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.logAndUpdateState(Uploader.java:164)
       at com.google.android.datatransport.runtime.ForcedSender.sendBlocking(ForcedSender.java:36)
       at com.google.firebase.crashlytics.internal.send.ReportQueue.lambda$flushScheduledReportsIfAble$0(ReportQueue.java:138)
       at java.lang.Thread.run(Thread.java:919)



Caused by android.database.sqlite.SQLiteDatabaseLockedException
database is locked (code 5 SQLITE_BUSY)
Caused by android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:648)
       at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:325)
       at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300)
       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:568)
       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:478)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.lambda$ensureBeginTransaction$24(SQLiteEventStore.java:755)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.retryIfDbLocked(SQLiteEventStore.java:582)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.ensureBeginTransaction(SQLiteEventStore.java:753)
       at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.runCriticalSection(SQLiteEventStore.java:766)
       at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.logAndUpdateState(Uploader.java:164)
       at com.google.android.datatransport.runtime.ForcedSender.sendBlocking(ForcedSender.java:36)
       at com.google.firebase.crashlytics.internal.send.ReportQueue.lambda$flushScheduledReportsIfAble$0(ReportQueue.java:138)
       at java.lang.Thread.run(Thread.java:919)
```

Here are some screenshots:

<img width="538" alt="image" src="https://github.com/firebase/firebase-android-sdk/assets/32784650/fda29587-d721-487e-bb17-f524dec13272">

<img width="1203" alt="image" src="https://github.com/firebase/firebase-android-sdk/assets/32784650/8d0f3751-5925-4b55-8e64-5517045a5e15">

<img width="1199" alt="image" src="https://github.com/firebase/firebase-android-sdk/assets/32784650/a965a78c-d566-4b14-a266-812c62838aac">

<img width="1201" alt="image" src="https://github.com/firebase/firebase-android-sdk/assets/32784650/211429d8-e8ce-4f10-8866-1b81e283a4ec">

Is there anything we could do ? Any insight would be appreciated.

**Comment by lehcar09** [comment]
Hi @lklong1551019, thank you for reaching out. Prior Firebase SDK version 31.3.0, the `flushScheduledReportsIfAble` was not catching errors with SQLExceptions. The fix ([#4608](https://github.com/firebase/firebase-android-sdk/pull/4608)) was included in the version BOM v31.3.0. You mentioned that you are using v32.8.0, did you notice if the issue has been reduced?

**Comment by lklong1551019** [comment]
Hi @lehcar09  , unfortunately the issue has not been reduced at all

**Comment by lklong1551019** [comment]
Hi @lehcar09 , here are some more insights on our crashlytics:

- After updating to 31.2.3, we have dozens of crash (30) per day
-  After updating to 32.8.0, the number of crashes is now about 300-400 perday

**Comment by lehcar09** [comment]
Thank you for the details @lklong1551019. I'll notify our engineers and see what we can do here. 

In the meantime, I would suggest using the latest Firebase SDK version to get the latest bug fixes and features.

**Comment by lklong1551019** [comment]
Thank you, glad to hear that. I'm looking forward to hearing updates. Cheers.

**Comment by anitdas** [comment]
Hi @lklong1551019! This issue is fixed in the latest bom (33.1.0). If you see this issue after updating, please file a new bug! Thanks :)

**Comment by lklong1551019** [comment]
Hi @anitdas , unfortunately we still have this issue so I just filed a new bug. I'm looking forward to hearing updates, thanks.
