### ISSUE TITLE
Fatal Exception: java.io.FileNotFoundException: open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by Ihor-SA** [firebase/firebase-android-sdk#7143]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Narwhal | 2025.1.1
  * Firebase Component: Crashlytics, Crashlytics-ndk, Messaging, Analytics
  * Component version: com.google.firebase:firebase-bom:33.15.0

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Duplicate of the issue [Permission deinied](https://github.com/firebase/firebase-android-sdk/issues/6611). Probably the issue is related to privacy changes in API level 29 (see image in the [comment](https://github.com/firebase/firebase-android-sdk/issues/6611#issuecomment-2574899309))

```          
Fatal Exception: java.io.FileNotFoundException: /data/data/<PACKAGE_NAME>/files/datastore/firebase_session_Y29tLnNlZWtpbmdhbHBoYS53ZWJ3cmFwcGVy_settings.preferences_pb: open failed: EACCES (Permission denied)
       at libcore.io.IoBridge.open(IoBridge.java:574)
       at java.io.FileInputStream.<init>(FileInputStream.java:179)
       at androidx.datastore.core.FileReadScope.readData$suspendImpl(FileStorage.kt:177)
       at androidx.datastore.core.FileReadScope.readData(FileReadScope.java:39)
       at androidx.datastore.core.StorageConnectionKt$readData$2.invokeSuspend(StorageConnection.kt:74)
       at androidx.datastore.core.StorageConnectionKt$readData$2.invoke(StorageConnection.kt:26)
       at androidx.datastore.core.StorageConnectionKt$readData$2.invoke(StorageConnection.kt:26)
       at androidx.datastore.core.FileStorageConnection.readScope(FileStorage.kt:101)
       at androidx.datastore.core.StorageConnectionKt.readData(StorageConnection.kt:74)
       at androidx.datastore.core.DataStoreImpl.readDataFromFileOrDefault(DataStoreImpl.kt:323)
       at androidx.datastore.core.DataStoreImpl.readDataOrHandleCorruption(DataStoreImpl.kt:365)
       at androidx.datastore.core.DataStoreImpl.access$readDataOrHandleCorruption(DataStoreImpl.kt:48)
       at androidx.datastore.core.DataStoreImpl$InitDataStore$doRun$initData$1.invokeSuspend(DataStoreImpl.kt:437)
       at androidx.datastore.core.DataStoreImpl$InitDataStore$doRun$initData$1.invoke(DataStoreImpl.kt:11)
       at androidx.datastore.core.DataStoreImpl$InitDataStore$doRun$initData$1.invoke(DataStoreImpl.kt:11)
       at androidx.datastore.core.SingleProcessCoordinator.lock(SingleProcessCoordinator.kt:41)
       at androidx.datastore.core.DataStoreImpl$InitDataStore.doRun(DataStoreImpl.java:434)
       at androidx.datastore.core.RunOnce.runIfNeeded(RunOnce.java:497)
       at androidx.datastore.core.DataStoreImpl.readAndInitOrPropagateAndThrowFailure(DataStoreImpl.kt:266)
       at androidx.datastore.core.DataStoreImpl.access$readAndInitOrPropagateAndThrowFailure(DataStoreImpl.kt:48)
       at androidx.datastore.core.DataStoreImpl$readState$2.invokeSuspend(DataStoreImpl.kt:218)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:124)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:586)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
```
```
Caused by android.system.ErrnoException: open failed: EACCES (Permission denied)
       at libcore.io.Linux.open(Linux.java)
       at libcore.io.ForwardingOs.open(ForwardingOs.java:568)
       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
       at libcore.io.ForwardingOs.open(ForwardingOs.java:568)
       at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:9367)
       at libcore.io.IoBridge.open(IoBridge.java:560)
       at java.io.FileInputStream.<init>(FileInputStream.java:179)
       at androidx.datastore.core.FileReadScope.readData$suspendImpl(FileStorage.kt:177)
       at androidx.datastore.core.FileReadScope.readData(FileReadScope.java:39)
       at androidx.datastore.core.StorageConnectionKt$readData$2.invokeSuspend(StorageConnection.kt:74)
       at androidx.datastore.core.StorageConnectionKt$readData$2.invoke(StorageConnection.kt:26)
       at androidx.datastore.core.StorageConnectionKt$readData$2.invoke(StorageConnection.kt:26)
       at androidx.datastore.core.FileStorageConnection.readScope(FileStorage.kt:101)
       at androidx.datastore.core.StorageConnectionKt.readData(StorageConnection.kt:74)
       at androidx.datastore.core.DataStoreImpl.readDataFromFileOrDefault(DataStoreImpl.kt:323)
       at androidx.datastore.core.DataStoreImpl.readDataOrHandleCorruption(DataStoreImpl.kt:365)
       at androidx.datastore.core.DataStoreImpl.access$readDataOrHandleCorruption(DataStoreImpl.kt:48)
       at androidx.datastore.core.DataStoreImpl$InitDataStore$doRun$initData$1.invokeSuspend(DataStoreImpl.kt:437)
       at androidx.datastore.core.DataStoreImpl$InitDataStore$doRun$initData$1.invoke(DataStoreImpl.kt:11)
       at androidx.datastore.core.DataStoreImpl$InitDataStore$doRun$initData$1.invoke(DataStoreImpl.kt:11)
       at androidx.datastore.core.SingleProcessCoordinator.lock(SingleProcessCoordinator.kt:41)
       at androidx.datastore.core.DataStoreImpl$InitDataStore.doRun(DataStoreImpl.java:434)
       at androidx.datastore.core.RunOnce.runIfNeeded(RunOnce.java:497)
       at androidx.datastore.core.DataStoreImpl.readAndInitOrPropagateAndThrowFailure(DataStoreImpl.kt:266)
       at androidx.datastore.core.DataStoreImpl.access$readAndInitOrPropagateAndThrowFailure(DataStoreImpl.kt:48)
       at androidx.datastore.core.DataStoreImpl$readState$2.invokeSuspend(DataStoreImpl.kt:218)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:124)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:586)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
```

#### Relevant Code:

```
No specific code.
```

**Comment by lehcar09** [comment]
Hi @Ihor-SA, thank you for reaching out. As mentioned in the #6611, this is an issue in the Datastore that is a Firebase dependency. 

Based on the public tracker (https://issuetracker.google.com/337870543), the issue is fixed in datastore v1.1.3. As of [BOM 33.11.0](https://firebase.google.com/support/release-notes/android#bom_v33-11-0) with [Crashlytics v19.4.2](https://firebase.google.com/support/release-notes/android#crashlytics_v19-4-2), we have updated the datastore dependency to v1.1.3. 

It would be best to reach out to the [Android Support team](https://developer.android.com/support) to raise this issue for investigation. Thanks!

**Comment by Ihor-SA** [comment]
hi @lehcar09 , thank you for your response, we are using firebase-bom:33.15.0 and the issue is still here, as I mentioned before probably the issue is related to privacy changes in API level 29
